blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://react-native-boilerplate-docs.vercel.app
    about: Check our comprehensive documentation first
  - name: 💬 GitHub Discussions
    url: https://github.com/sohantalukder/react-native-boilerplate/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Email Support
    url: mailto:mdtalukder.sohan@gmail.com
    about: Contact the maintainer directly for urgent issues 